//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./nodeService_types');
//HELPER FUNCTIONS AND STRUCTURES

TNodeService_queryFileUrls_args = function(args) {
  this.profile = null;
  if (args) {
    if (args.profile !== undefined && args.profile !== null) {
      this.profile = args.profile;
    }
  }
};
TNodeService_queryFileUrls_args.prototype = {};
TNodeService_queryFileUrls_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.profile = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TNodeService_queryFileUrls_args.prototype.write = function(output) {
  output.writeStructBegin('TNodeService_queryFileUrls_args');
  if (this.profile !== null && this.profile !== undefined) {
    output.writeFieldBegin('profile', Thrift.Type.STRING, 1);
    output.writeString(this.profile);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TNodeService_queryFileUrls_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [null]);
    }
  }
};
TNodeService_queryFileUrls_result.prototype = {};
TNodeService_queryFileUrls_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readString();
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TNodeService_queryFileUrls_result.prototype.write = function(output) {
  output.writeStructBegin('TNodeService_queryFileUrls_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRING, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        output.writeString(iter7);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TNodeService_queryFilePatchUrls_args = function(args) {
  this.profile = null;
  if (args) {
    if (args.profile !== undefined && args.profile !== null) {
      this.profile = args.profile;
    }
  }
};
TNodeService_queryFilePatchUrls_args.prototype = {};
TNodeService_queryFilePatchUrls_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.profile = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TNodeService_queryFilePatchUrls_args.prototype.write = function(output) {
  output.writeStructBegin('TNodeService_queryFilePatchUrls_args');
  if (this.profile !== null && this.profile !== undefined) {
    output.writeFieldBegin('profile', Thrift.Type.STRING, 1);
    output.writeString(this.profile);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TNodeService_queryFilePatchUrls_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [null]);
    }
  }
};
TNodeService_queryFilePatchUrls_result.prototype = {};
TNodeService_queryFilePatchUrls_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.success = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = input.readString();
          this.success.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TNodeService_queryFilePatchUrls_result.prototype.write = function(output) {
  output.writeStructBegin('TNodeService_queryFilePatchUrls_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRING, this.success.length);
    for (var iter15 in this.success)
    {
      if (this.success.hasOwnProperty(iter15))
      {
        iter15 = this.success[iter15];
        output.writeString(iter15);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TNodeServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
TNodeServiceClient.prototype = {};
TNodeServiceClient.prototype.seqid = function() { return this._seqid; }
TNodeServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
TNodeServiceClient.prototype.queryFileUrls = function(profile, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_queryFileUrls(profile);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_queryFileUrls(profile);
  }
};

TNodeServiceClient.prototype.send_queryFileUrls = function(profile) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('queryFileUrls', Thrift.MessageType.CALL, this.seqid());
  var args = new TNodeService_queryFileUrls_args();
  args.profile = profile;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TNodeServiceClient.prototype.recv_queryFileUrls = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TNodeService_queryFileUrls_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('queryFileUrls failed: unknown result');
};
TNodeServiceClient.prototype.queryFilePatchUrls = function(profile, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_queryFilePatchUrls(profile);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_queryFilePatchUrls(profile);
  }
};

TNodeServiceClient.prototype.send_queryFilePatchUrls = function(profile) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('queryFilePatchUrls', Thrift.MessageType.CALL, this.seqid());
  var args = new TNodeService_queryFilePatchUrls_args();
  args.profile = profile;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TNodeServiceClient.prototype.recv_queryFilePatchUrls = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TNodeService_queryFilePatchUrls_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('queryFilePatchUrls failed: unknown result');
};
TNodeServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
TNodeServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

TNodeServiceProcessor.prototype.process_queryFileUrls = function(seqid, input, output) {
  var args = new TNodeService_queryFileUrls_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.queryFileUrls.length === 1) {
    Q.fcall(this._handler.queryFileUrls, args.profile)
      .then(function(result) {
        var result = new TNodeService_queryFileUrls_result({success: result});
        output.writeMessageBegin("queryFileUrls", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("queryFileUrls", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.queryFileUrls(args.profile, function (err, result) {
      if (err == null) {
        var result = new TNodeService_queryFileUrls_result((err != null ? err : {success: result}));
        output.writeMessageBegin("queryFileUrls", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("queryFileUrls", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

TNodeServiceProcessor.prototype.process_queryFilePatchUrls = function(seqid, input, output) {
  var args = new TNodeService_queryFilePatchUrls_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.queryFilePatchUrls.length === 1) {
    Q.fcall(this._handler.queryFilePatchUrls, args.profile)
      .then(function(result) {
        var result = new TNodeService_queryFilePatchUrls_result({success: result});
        output.writeMessageBegin("queryFilePatchUrls", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("queryFilePatchUrls", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.queryFilePatchUrls(args.profile, function (err, result) {
      if (err == null) {
        var result = new TNodeService_queryFilePatchUrls_result((err != null ? err : {success: result}));
        output.writeMessageBegin("queryFilePatchUrls", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("queryFilePatchUrls", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

